spring.datasource.url=jdbc:postgresql://localhost:5432/telegrambot
spring.datasource.username=karlitoz_bot
spring.datasource.password=StrongPass123!
telegram.bot.token=8212375777:AAEsXn-zKiLcdvyO6VfXNFHLddVLI3rItBA
spring.jpa.hibernate.ddl-auto=update

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.default-schema=public